zellij

diff --git a/bin/bin/scheme b/bin/bin/scheme
--- a/bin/bin/scheme
+++ b/bin/bin/scheme
@@ -28,6 +28,7 @@ main() {
         gtk_theme
         iterm2_scheme
         vim_theme
+        zellij_theme
         xterm_colors
     )
 
@@ -97,7 +98,8 @@ set_scheme() {
 
     update_emacs "$emacs_theme" "$background" &
     update_vim "$vim_theme" "$background" &
-    #update_tmux "$scheme" "$background" &
+    update_honeymux "$scheme" "$background" &
+    update_zellij "$zellij_theme" &
     update_bat "$bat_theme"
     update_delta "$bat_theme"
 
@@ -165,6 +167,7 @@ load_default_schemes() {
     light_emacs_theme=spacemacs-light # doom-one-light
     light_vim_theme=alabaster # default
     light_bat_theme=GitHub
+    light_zellij_theme=pencil-light
     light_toggle=dark
 
     dark_background=dark
@@ -176,6 +179,7 @@ load_default_schemes() {
     dark_emacs_theme=spacemacs-dark # doom-one
     dark_vim_theme=alabaster # inkpot
     dark_bat_theme='Monokai Extended' # default
+    dark_zellij_theme=default
     dark_toggle=light
 
     tokyonight_background=dark
@@ -184,6 +188,7 @@ load_default_schemes() {
                              #9ece6a #e0af68 #7aa2f7 #bb9af7 #7dcfff #c0caf5
                              #f7768e"
     tokyonight_vim_theme=tokyonight
+    tokyonight_zellij_theme=tokyonight
     tokyonight_toggle=tokyoday
     # background #1a1b26
     # selection_background #283457
@@ -212,6 +217,7 @@ load_default_schemes() {
     solarized_light_emacs_theme=solarized
     solarized_light_vim_theme=NeoSolarized
     solarized_light_bat_theme='Solarized (light)'
+    solarized_light_zellij_theme=solarized-light
     solarized_light_toggle=solarized_dark
 
     solarized_dark_background=dark
@@ -223,7 +229,8 @@ load_default_schemes() {
     #xterm_cursor="#93a1a1"  XXX
     solarized_dark_emacs_theme=solarized
     solarized_dark_vim_theme=NeoSolarized
-    solarized_light_bat_theme='Solarized (dark)'
+    solarized_dark_bat_theme='Solarized (dark)'
+    solarized_dark_zellij_theme=solarized-dark
     solarized_dark_toggle=solarized_light
 
     darcula_background=dark
@@ -342,15 +349,35 @@ update_vim() {
     echo "$background" > ~/.vim/background
 }
 
-update_tmux() {
-    declare x scheme="$1" background="$2"
+update_honeymux() {
+    declare scheme="$1" background="$2"
 
-    tmux info &>/dev/null || return
+    tmux -L honeymux info &>/dev/null || return
 
-    case "$scheme:$background" in
-        solarized*|*:dark) tmux set -g status-style fg=default,bg=default ;;
-        *:light) tmux set -g status-style fg=default,bg=white,dim ;;
-    esac
+    # unpack xterm_colors string
+    declare xterm_foreground xterm_background
+    xterm_colors=( $xterm_colors )
+    if [[ ${#xterm_colors[@]} -lt 2 ]]; then
+        echo "Invalid xterm_colors (${#xterm_colors[@]} elements)" >&2
+        return
+    fi
+    xterm_background="${xterm_colors[0]}"
+    xterm_foreground="${xterm_colors[1]}"
+
+    cat > ~/.tmux/theme <<EOT
+# This file is automatically generated by bin/scheme
+set -g window-style 'fg=${xterm_foreground},bg=${xterm_background}'
+set -g window-active-style 'fg=${xterm_foreground},bg=${xterm_background}'
+EOT
+
+    tmux -L honeymux source-file ~/.tmux/theme
+}
+
+update_zellij() {
+    declare theme="$1"
+    if [[ -f ~/.config/zellij/config.kdl ]]; then
+        sed -i "s/^theme .*/theme \"$theme\"/" ~/.config/zellij/config.kdl
+    fi
 }
 
 after_update_hook() {
